version: "3.7"
services:
  app:
    build: .
    volumes:
      - ./backend:/srv/backend/
    ports:
      - "8000:8000"
    command: sh -c "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
